# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 10:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Укажите Ваше имя', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Укажите Вашу фамилию', max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(help_text='Укажите Ваш электронный адрес', max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(help_text='Укажите Ваш номер телефона в формате: +79998887766', max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона необходимо вводить в формате: '+799999999'. До 15 цифр.", regex='^\\+?1?\\d{7,15}$')], verbose_name='Номер телефона')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Почтовый индекс')),
                ('address', models.CharField(help_text='Укажите Ваш адрес в формате: Улица, Дом, Корпус, Квартира', max_length=250, verbose_name='Адрес')),
                ('comments', models.TextField(blank=True, default=None, null=True, verbose_name='Комментарии к заказу')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Колличество')),
                ('price_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая стоимость')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активирован/Деактивирован')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Status', verbose_name='Статус'),
        ),
    ]
